import AdminPageHeader from '@/Components/AdminPageHeader';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import EditorLayout from '@/Layouts/EditorLayout';
import { Head, Link, router } from '@inertiajs/react';

interface Candidate { id:number; title:string; summary:string|null; source_hint:string|null; source_url:string|null; relevance_score:number; editorial_angle:string|null; why_it_matters:string|null; sort_order:number; is_selected:boolean; news_item_id:number|null; suggested_category?:{name:string}|null; suggested_location?:{name:string}|null; }
interface R { id:number; title:string; status:string; prompt_snapshot:string|null; response_snapshot:string|null; parsed_response:any; error_message:string|null; candidates:Candidate[]; }

export default function Show({ requestItem }: { requestItem:R }): JSX.Element {
    return <EditorLayout><Head title={requestItem.title} /><AdminPageHeader title={requestItem.title} description="Editorial request details." actionLabel="Edit" actionHref={route('editor.editorial-requests.edit', requestItem.id)} />
        <div className="mb-4 flex flex-wrap gap-2"><Button onClick={()=>router.post(route('editor.editorial-requests.run', requestItem.id))}>Run Request</Button><Button variant="secondary" onClick={()=>router.post(route('editor.editorial-requests.create-news-items', requestItem.id))}>Create News Items</Button><Button variant="outline" onClick={()=>router.post(route('editor.editorial-requests.convert-to-edition', requestItem.id))}>Convert to Edition</Button><Button asChild variant="ghost"><Link href={route('editor.editorial-requests.index')}>Back</Link></Button></div>
        <Card><CardContent className="space-y-3 pt-6 text-sm"><p><strong>Status:</strong> {requestItem.status}</p>{requestItem.error_message && <p className="text-red-600"><strong>Error:</strong> {requestItem.error_message}</p>}<div><strong>Prompt snapshot</strong><pre className="mt-1 whitespace-pre-wrap rounded bg-slate-100 p-3">{requestItem.prompt_snapshot || '-'}</pre></div><div><strong>Response snapshot</strong><pre className="mt-1 whitespace-pre-wrap rounded bg-slate-100 p-3">{requestItem.response_snapshot || '-'}</pre></div><div><strong>Parsed response</strong><pre className="mt-1 whitespace-pre-wrap rounded bg-slate-100 p-3">{requestItem.parsed_response ? JSON.stringify(requestItem.parsed_response, null, 2) : '-'}</pre></div></CardContent></Card>
        <Card className="mt-4"><CardContent className="pt-6"><h3 className="mb-3 text-base font-semibold">Candidate News</h3><div className="space-y-3">{requestItem.candidates.length ? requestItem.candidates.map((candidate)=><div key={candidate.id} className="rounded border border-slate-200 p-3 text-sm"><p className="font-semibold">{candidate.title}</p><p>{candidate.summary || '-'}</p><p><strong>Source hint:</strong> {candidate.source_hint || '-'}</p><p><strong>Source URL:</strong> {candidate.source_url || '-'}</p><p><strong>Category:</strong> {candidate.suggested_category?.name || '-'}</p><p><strong>Location:</strong> {candidate.suggested_location?.name || '-'}</p><p><strong>Relevance score:</strong> {candidate.relevance_score}</p><p><strong>Editorial angle:</strong> {candidate.editorial_angle || '-'}</p><p><strong>Why it matters:</strong> {candidate.why_it_matters || '-'}</p><p><strong>Selected:</strong> {candidate.is_selected ? 'Yes' : 'No'}</p></div>) : <p>No candidates found.</p>}</div></CardContent></Card>
    </EditorLayout>;
}
