import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { useTranslations } from '@/i18n/useTranslations';
import { Link, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

interface Option { id:number; name:string; code?:string }
interface Schedule { id:number; name:string; slug:string|null; description:string|null; location_id:number|null; news_category_id:number|null; language_id:number|null; editorial_template_id?:number|null; ai_prompt_template_id?:number|null; edition_type:string; frequency_type:string; scheduled_time:string|null; scheduled_date:string|null; weekdays:string[]|null; timezone:string|null; target_duration_seconds:number|null; tone:string|null; manual_ai_mode:boolean; is_active:boolean; editorial_instructions:string|null; output_instructions:string|null; }

export default function Form({ schedule, locations, categories, languages, editorialTemplates, aiPromptTemplates, frequencyTypes, editionTypes }: { schedule?:Schedule; locations:Option[]; categories:Option[]; languages:Option[]; editorialTemplates:Option[]; aiPromptTemplates:Option[]; frequencyTypes:string[]; editionTypes:string[] }): JSX.Element {
  const isEdit = !!schedule; const { t } = useTranslations();
  const form = useForm({
    name: schedule?.name ?? '', slug: schedule?.slug ?? '', description: schedule?.description ?? '', location_id: schedule?.location_id ? String(schedule.location_id) : '', news_category_id: schedule?.news_category_id ? String(schedule.news_category_id) : '', language_id: schedule?.language_id ? String(schedule.language_id) : '', editorial_template_id: schedule?.editorial_template_id ? String(schedule.editorial_template_id) : '', ai_prompt_template_id: schedule?.ai_prompt_template_id ? String(schedule.ai_prompt_template_id) : '', edition_type: schedule?.edition_type ?? 'morning', frequency_type: schedule?.frequency_type ?? 'daily', scheduled_time: schedule?.scheduled_time ? schedule.scheduled_time.slice(0,5) : '', scheduled_date: schedule?.scheduled_date ? schedule.scheduled_date.slice(0,10) : '', weekdays: schedule?.weekdays ?? [], timezone: schedule?.timezone ?? '', target_duration_seconds: schedule?.target_duration_seconds ? String(schedule.target_duration_seconds) : '', tone: schedule?.tone ?? '', manual_ai_mode: schedule?.manual_ai_mode ?? true, is_active: schedule?.is_active ?? true, editorial_instructions: schedule?.editorial_instructions ?? '', output_instructions: schedule?.output_instructions ?? '',
  });

  const toggleWeekday = (day: string): void => {
    const current = form.data.weekdays || [];
    form.setData('weekdays', current.includes(day) ? current.filter((d) => d !== day) : [...current, day]);
  };
  const submit = (e:FormEvent)=>{e.preventDefault(); isEdit ? form.put(route('editor.editorial-schedules.update', schedule!.id)) : form.post(route('editor.editorial-schedules.store'));};
  const weekdays = [{key:'mon',label:t('Monday')},{key:'tue',label:t('Tuesday')},{key:'wed',label:t('Wednesday')},{key:'thu',label:t('Thursday')},{key:'fri',label:t('Friday')},{key:'sat',label:t('Saturday')},{key:'sun',label:t('Sunday')}];

  return <form onSubmit={submit} className="space-y-4">
    <div className="grid gap-4 md:grid-cols-2"><div><Label>{t('Name')}</Label><Input value={form.data.name} onChange={(e)=>form.setData('name', e.target.value)} /></div><div><Label>{t('Slug')}</Label><Input value={form.data.slug} onChange={(e)=>form.setData('slug', e.target.value)} /></div></div>
    <div><Label>{t('Description')}</Label><textarea className="w-full rounded-md border border-slate-300 px-3 py-2" rows={3} value={form.data.description} onChange={(e)=>form.setData('description', e.target.value)} /></div>
    <div className="grid gap-4 md:grid-cols-3"><div><Label>{t('Location')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.location_id} onChange={(e)=>form.setData('location_id', e.target.value)}><option value="">-</option>{locations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><div><Label>{t('Category')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.news_category_id} onChange={(e)=>form.setData('news_category_id', e.target.value)}><option value="">-</option>{categories.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><div><Label>{t('Language')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.language_id} onChange={(e)=>form.setData('language_id', e.target.value)}><option value="">-</option>{languages.map(o=><option key={o.id} value={o.id}>{o.name} {o.code ? `(${o.code})`:''}</option>)}</select></div></div>
    <div className="grid gap-4 md:grid-cols-2"><div><Label>{t('Editorial Template')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.editorial_template_id} onChange={(e)=>form.setData('editorial_template_id', e.target.value)}><option value="">-</option>{editorialTemplates.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><div><Label>{t('Prompt Template')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.ai_prompt_template_id} onChange={(e)=>form.setData('ai_prompt_template_id', e.target.value)}><option value="">-</option>{aiPromptTemplates.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div></div>
    <div className="grid gap-4 md:grid-cols-3"><div><Label>{t('Edition type')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.edition_type} onChange={(e)=>form.setData('edition_type', e.target.value)}>{editionTypes.map(item=><option key={item} value={item}>{t(item.charAt(0).toUpperCase()+item.slice(1))}</option>)}</select></div><div><Label>{t('Frequency type')}</Label><select className="w-full rounded-md border border-slate-300 px-3 py-2" value={form.data.frequency_type} onChange={(e)=>form.setData('frequency_type', e.target.value)}>{frequencyTypes.map(item=><option key={item} value={item}>{t(item.charAt(0).toUpperCase()+item.slice(1))}</option>)}</select></div><div><Label>{t('Target duration')}</Label><Input type="number" min={15} max={3600} value={form.data.target_duration_seconds} onChange={(e)=>form.setData('target_duration_seconds', e.target.value)} /></div></div>
    <div className="grid gap-4 md:grid-cols-3"><div><Label>{t('Scheduled time')}</Label><Input type="time" value={form.data.scheduled_time} onChange={(e)=>form.setData('scheduled_time', e.target.value)} /></div><div><Label>{t('Scheduled date')}</Label><Input type="date" value={form.data.scheduled_date} onChange={(e)=>form.setData('scheduled_date', e.target.value)} /></div><div><Label>{t('Timezone')}</Label><Input value={form.data.timezone} onChange={(e)=>form.setData('timezone', e.target.value)} /></div></div>
    <div><Label>{t('Weekdays')}</Label><div className="mt-2 flex flex-wrap gap-3">{weekdays.map((day)=><label key={day.key} className="text-sm"><input type="checkbox" className="mr-1" checked={(form.data.weekdays || []).includes(day.key)} onChange={()=>toggleWeekday(day.key)} />{day.label}</label>)}</div></div>
    <div className="grid gap-4 md:grid-cols-2"><div><Label>{t('Tone')}</Label><Input value={form.data.tone} onChange={(e)=>form.setData('tone', e.target.value)} /></div><div className="flex items-end gap-4"><label className="text-sm"><input type="checkbox" className="mr-1" checked={form.data.manual_ai_mode} onChange={(e)=>form.setData('manual_ai_mode', e.target.checked)} />{t('Manual AI Mode')}</label><label className="text-sm"><input type="checkbox" className="mr-1" checked={form.data.is_active} onChange={(e)=>form.setData('is_active', e.target.checked)} />{t('Active')}</label></div></div>
    <div><Label>{t('Editorial instructions')}</Label><textarea className="w-full rounded-md border border-slate-300 px-3 py-2" rows={4} value={form.data.editorial_instructions} onChange={(e)=>form.setData('editorial_instructions', e.target.value)} /></div>
    <div><Label>{t('Output instructions')}</Label><textarea className="w-full rounded-md border border-slate-300 px-3 py-2" rows={4} value={form.data.output_instructions} onChange={(e)=>form.setData('output_instructions', e.target.value)} /></div>
    <div className="flex gap-2"><Button disabled={form.processing} type="submit">{t('Save')}</Button><Button asChild variant="secondary"><Link href={route('editor.editorial-schedules.index')}>{t('Cancel')}</Link></Button></div>
  </form>;
}
