import AdminPageHeader from '@/Components/AdminPageHeader';
import Pagination from '@/Components/Pagination';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import { useTranslations } from '@/i18n/useTranslations';
import EditorLayout from '@/Layouts/EditorLayout';
import { Head, Link, router } from '@inertiajs/react';

interface Schedule { id:number; name:string; bulletin_type?:{name:string}|null; run_frequency?:string|null; next_run_at?:string|null; last_run_at?:string|null; is_active:boolean; auto_create_prompt_run?:boolean; auto_generate_prompt?:boolean }
export default function Index({ schedules }: { schedules:{ data:Schedule[]; links:Array<{url:string|null;label:string;active:boolean}> } }): JSX.Element {
 const { t } = useTranslations();
 const destroy=(id:number)=>{ if(window.confirm(t('Delete schedule?'))) router.delete(route('editor.editorial-schedules.destroy', id)); };
 return <EditorLayout><Head title={t('Editorial Schedules')} /><AdminPageHeader helpKey="editor.editorialschedules.index" title={t('Editorial Schedules')} description={t('Automatic schedule runner')} actionLabel={t('Create Schedule')} actionHref={route('editor.editorial-schedules.create')} /><Card><CardContent className="overflow-x-auto pt-6"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b"><th className="px-2 pb-3 text-left">{t('Name')}</th><th>{t('Bulletin Types')}</th><th>{t('Run frequency')}</th><th>{t('Next scheduled run')}</th><th>{t('Last scheduled run')}</th><th>{t('Active')}</th><th>{t('Auto create prompt run')}</th><th>{t('Auto generate prompt')}</th><th className="text-right">{t('Actions')}</th></tr></thead><tbody>{schedules.data.length ? schedules.data.map((item)=><tr key={item.id} className="border-b"><td className="px-2 py-3">{item.name}</td><td>{item.bulletin_type?.name || '-'}</td><td>{item.run_frequency || '-'}</td><td>{item.next_run_at ? item.next_run_at.slice(0,16).replace('T',' ') : '-'}</td><td>{item.last_run_at ? item.last_run_at.slice(0,16).replace('T',' ') : '-'}</td><td>{item.is_active ? t('Yes') : t('No')}</td><td>{item.auto_create_prompt_run ? t('Yes') : t('No')}</td><td>{item.auto_generate_prompt ? t('Yes') : t('No')}</td><td className="py-2 text-right"><div className="flex justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={route('editor.editorial-schedules.show', item.id)}>{t('Show')}</Link></Button><Button asChild size="sm" variant="secondary"><Link href={route('editor.editorial-schedules.edit', item.id)}>{t('Edit')}</Link></Button><Button size="sm" variant="destructive" onClick={()=>destroy(item.id)}>{t('Delete')}</Button></div></td></tr>) : <tr><td colSpan={9} className="px-2 py-6 text-center">{t('No schedules found')}</td></tr>}</tbody></table><Pagination links={schedules.links} /></CardContent></Card></EditorLayout>;
}
