import AdminPageHeader from '@/Components/AdminPageHeader';
import Pagination from '@/Components/Pagination';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import { useTranslations } from '@/i18n/useTranslations';
import EditorLayout from '@/Layouts/EditorLayout';
import { Head, Link, router } from '@inertiajs/react';

interface Schedule { id:number; name:string; location?:{name:string}|null; news_category?:{name:string}|null; language?:{code:string}|null; edition_type:string; frequency_type:string; scheduled_time:string|null; scheduled_date:string|null; weekdays:string[]|null; is_active:boolean; manual_ai_mode:boolean }
export default function Index({ schedules }: { schedules:{ data:Schedule[]; links:Array<{url:string|null;label:string;active:boolean}> } }): JSX.Element {
 const { t } = useTranslations();
 const destroy=(id:number)=>{ if(window.confirm('Delete schedule?')) router.delete(route('editor.editorial-schedules.destroy', id)); };
 return <EditorLayout><Head title={t('Editorial Schedules')} /><AdminPageHeader title={t('Editorial Schedules')} description="Configurable schedule definitions for manual AI workflow." actionLabel={t('Create Schedule')} actionHref={route('editor.editorial-schedules.create')} /><Card><CardContent className="overflow-x-auto pt-6"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b"><th className="px-2 pb-3 text-left">{t('Name')}</th><th className="px-2 pb-3 text-left">{t('Location')}</th><th className="px-2 pb-3 text-left">{t('Category')}</th><th className="px-2 pb-3 text-left">{t('Language')}</th><th className="px-2 pb-3 text-left">{t('Edition type')}</th><th className="px-2 pb-3 text-left">{t('Frequency')}</th><th className="px-2 pb-3 text-left">{t('Scheduled time')}</th><th className="px-2 pb-3 text-left">{t('Scheduled date')}</th><th className="px-2 pb-3 text-left">{t('Weekdays')}</th><th className="px-2 pb-3 text-left">{t('Active')}</th><th className="px-2 pb-3 text-left">{t('Manual AI Mode')}</th><th className="px-2 pb-3 text-right">{t('Actions')}</th></tr></thead><tbody>{schedules.data.length ? schedules.data.map((item)=><tr key={item.id} className="border-b"><td className="px-2 py-3">{item.name}</td><td className="px-2 py-3">{item.location?.name || '-'}</td><td className="px-2 py-3">{item.news_category?.name || '-'}</td><td className="px-2 py-3">{item.language?.code || '-'}</td><td className="px-2 py-3">{item.edition_type}</td><td className="px-2 py-3">{item.frequency_type}</td><td className="px-2 py-3">{item.scheduled_time?.slice(0,5) || '-'}</td><td className="px-2 py-3">{item.scheduled_date?.slice(0,10) || '-'}</td><td className="px-2 py-3">{item.weekdays?.join(', ') || '-'}</td><td className="px-2 py-3">{item.is_active ? t('Yes') : t('No')}</td><td className="px-2 py-3">{item.manual_ai_mode ? t('Yes') : t('No')}</td><td className="px-2 py-3"><div className="flex justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={route('editor.editorial-schedules.show', item.id)}>{t('Show')}</Link></Button><Button asChild size="sm" variant="secondary"><Link href={route('editor.editorial-schedules.edit', item.id)}>{t('Edit')}</Link></Button><Button size="sm" variant="destructive" onClick={()=>destroy(item.id)}>{t('Delete')}</Button></div></td></tr>) : <tr><td colSpan={12} className="px-2 py-6 text-center">No schedules found.</td></tr>}</tbody></table><Pagination links={schedules.links} /></CardContent></Card></EditorLayout>;
}
