import AdminPageHeader from '@/Components/AdminPageHeader';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { useTranslations } from '@/i18n/useTranslations';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, useForm } from '@inertiajs/react';

const CAPABILITIES = ['script_generation','news_grounding','google_search_grounding','citations','tts','speech_synthesis','video_render','media_processing','local_processing','fast_inference','mock'];
const CATEGORIES = ['text','grounded_text','audio','video','media','local','testing','moderation','publishing','other'];

export default function AiProviderForm({ provider, providerTypes = [] }: any): JSX.Element {
  const isEdit = !!provider; const { t } = useTranslations();
  const form = useForm({ ...provider, name: provider?.name ?? '', slug: provider?.slug ?? '', provider_type: provider?.provider_type ?? 'groq', provider_category: provider?.provider_category ?? 'text', capabilities: provider?.capabilities ?? [], timeout_seconds: String(provider?.timeout_seconds ?? 60), max_tokens: provider?.max_tokens ?? '', temperature: provider?.temperature ?? '', daily_request_limit: provider?.daily_request_limit ?? '', monthly_request_limit: provider?.monthly_request_limit ?? '', cost_input_per_1k_tokens: provider?.cost_input_per_1k_tokens ?? '', cost_output_per_1k_tokens: provider?.cost_output_per_1k_tokens ?? '', api_key_env_name: provider?.api_key_env_name ?? '', default_model: provider?.default_model ?? '', base_url: provider?.base_url ?? '', is_active: provider?.is_active ?? true, is_default: provider?.is_default ?? false, is_testing: provider?.is_testing ?? false, is_local: provider?.is_local ?? false, supports_grounding: provider?.supports_grounding ?? false, supports_citations: provider?.supports_citations ?? false, supports_streaming: provider?.supports_streaming ?? false, requests_per_minute_limit: provider?.requests_per_minute_limit ?? '', requests_per_day_limit: provider?.requests_per_day_limit ?? '', tokens_per_minute_limit: provider?.tokens_per_minute_limit ?? '', min_seconds_between_requests: provider?.min_seconds_between_requests ?? '', retry_on_rate_limit: provider?.retry_on_rate_limit ?? true, max_retries: provider?.max_retries ?? 5, initial_retry_delay_seconds: provider?.initial_retry_delay_seconds ?? 5, max_retry_delay_seconds: provider?.max_retry_delay_seconds ?? 300, backoff_multiplier: provider?.backoff_multiplier ?? 2, jitter_enabled: provider?.jitter_enabled ?? true });
  const error=(k:string)=>form.errors[k] ? <p className='text-xs text-red-600'>{form.errors[k]}</p>:null;
  return <AdminLayout><Head title={isEdit?t('Edit AI Provider'):t('Create AI Provider')} /><AdminPageHeader helpKey='admin.aiproviders.form' title={isEdit?t('Edit AI Provider'):t('Create AI Provider')} description={t('Validation errors')} />
  <Card><CardContent className='pt-6'><form className='space-y-4' onSubmit={e=>{e.preventDefault(); isEdit?form.put(route('admin.ai-providers.update', provider.id)):form.post(route('admin.ai-providers.store'));}}>
  <div className='grid md:grid-cols-2 gap-4'><div><Label>{t('Name')} *</Label><Input value={form.data.name} onChange={e=>form.setData('name', e.target.value)} />{error('name')}</div><div><Label>{t('Slug')} *</Label><Input value={form.data.slug} onChange={e=>form.setData('slug', e.target.value)} />{error('slug')}</div></div>
  <div className='grid md:grid-cols-3 gap-4'><div><Label>{t('Provider type')} *</Label><select className='w-full border rounded-md px-3 py-2' value={form.data.provider_type} onChange={e=>form.setData('provider_type',e.target.value)}>{providerTypes.map((x:string)=><option key={x} value={x}>{x}</option>)}</select>{error('provider_type')}</div><div><Label>{t('Provider category')} *</Label><select className='w-full border rounded-md px-3 py-2' value={form.data.provider_category} onChange={e=>form.setData('provider_category', e.target.value)}>{CATEGORIES.map((x)=><option key={x} value={x}>{t(x==='text'?'Scripts / Text':x==='grounded_text'?'News with search and sources':x==='audio'?'Audio / Voice':x==='video'?'Video':x==='media'?'Media processing':x==='local'?'Local / Offline':x==='testing'?'Testing':x==='moderation'?'Review / Moderation':x==='publishing'?'Publishing':'Other')}</option>)}</select>{error('provider_category')}</div><div><Label>{t('Default model')}</Label><Input value={form.data.default_model} onChange={e=>form.setData('default_model', e.target.value)} />{error('default_model')}</div></div>
  <div className='grid md:grid-cols-2 gap-4'><div><Label>{t('Base URL')}</Label><Input value={form.data.base_url ?? ''} onChange={e=>form.setData('base_url', e.target.value)} />{error('base_url')}</div><div><Label>{t('API key environment name')}</Label><Input value={form.data.api_key_env_name ?? ''} onChange={e=>form.setData('api_key_env_name', e.target.value)} />{error('api_key_env_name')}</div></div>
  <div><Label>{t('Provider capabilities')}</Label><div className='grid grid-cols-2 md:grid-cols-4 gap-2 mt-2'>{CAPABILITIES.map((c)=><label key={c} className='text-sm flex gap-2 items-center'><input type='checkbox' checked={form.data.capabilities.includes(c)} onChange={e=>form.setData('capabilities', e.target.checked?[...form.data.capabilities,c]:form.data.capabilities.filter((x:string)=>x!==c))} />{t(c==='script_generation'?'Script generation':c==='news_grounding'?'News grounding':c==='google_search_grounding'?'Google Search grounding':c==='citations'?'Citations':c==='tts'?'Text to speech':c==='speech_synthesis'?'Speech synthesis':c==='video_render'?'Video rendering':c==='media_processing'?'Media processing':c==='local_processing'?'Local processing':c==='fast_inference'?'Fast inference':c)}</label>)}</div>{error('capabilities')}</div><div className='grid md:grid-cols-3 gap-4'><div><Label>{t('Daily request limit')}</Label><Input type='number' value={form.data.daily_request_limit} onChange={e=>form.setData('daily_request_limit', e.target.value)} />{error('daily_request_limit')}</div><div><Label>{t('Monthly request limit')}</Label><Input type='number' value={form.data.monthly_request_limit} onChange={e=>form.setData('monthly_request_limit', e.target.value)} />{error('monthly_request_limit')}</div><div><Label>{t('Timeout seconds')}</Label><Input type='number' value={form.data.timeout_seconds} onChange={e=>form.setData('timeout_seconds', e.target.value)} />{error('timeout_seconds')}</div></div><div className='grid md:grid-cols-4 gap-4'><div><Label>{t('Max tokens')}</Label><Input type='number' value={form.data.max_tokens} onChange={e=>form.setData('max_tokens', e.target.value)} />{error('max_tokens')}</div><div><Label>{t('Temperature')}</Label><Input type='number' step='0.1' value={form.data.temperature} onChange={e=>form.setData('temperature', e.target.value)} />{error('temperature')}</div><div><Label>{t('Input token cost')}</Label><Input type='number' step='0.000001' value={form.data.cost_input_per_1k_tokens} onChange={e=>form.setData('cost_input_per_1k_tokens', e.target.value)} />{error('cost_input_per_1k_tokens')}</div><div><Label>{t('Output token cost')}</Label><Input type='number' step='0.000001' value={form.data.cost_output_per_1k_tokens} onChange={e=>form.setData('cost_output_per_1k_tokens', e.target.value)} />{error('cost_output_per_1k_tokens')}</div></div>
<div className='space-y-2'><h4 className='font-semibold'>{t('Rate limit settings')}</h4><div className='grid md:grid-cols-4 gap-4'><div><Label>{t('Requests per minute')}</Label><Input type='number' value={form.data.requests_per_minute_limit} onChange={e=>form.setData('requests_per_minute_limit', e.target.value)} /></div><div><Label>{t('Requests per day')}</Label><Input type='number' value={form.data.requests_per_day_limit} onChange={e=>form.setData('requests_per_day_limit', e.target.value)} /></div><div><Label>{t('Tokens per minute')}</Label><Input type='number' value={form.data.tokens_per_minute_limit} onChange={e=>form.setData('tokens_per_minute_limit', e.target.value)} /></div><div><Label>{t('Minimum seconds between requests')}</Label><Input type='number' value={form.data.min_seconds_between_requests} onChange={e=>form.setData('min_seconds_between_requests', e.target.value)} /></div></div></div><div className='space-y-2'><h4 className='font-semibold'>{t('Retry policy')}</h4><div className='grid md:grid-cols-4 gap-4'><label><input type='checkbox' checked={form.data.retry_on_rate_limit} onChange={e=>form.setData('retry_on_rate_limit', e.target.checked)} /> {t('Retry on rate limit')}</label><div><Label>{t('Max retries')}</Label><Input type='number' value={form.data.max_retries} onChange={e=>form.setData('max_retries', e.target.value)} /></div><div><Label>{t('Initial retry delay')}</Label><Input type='number' value={form.data.initial_retry_delay_seconds} onChange={e=>form.setData('initial_retry_delay_seconds', e.target.value)} /></div><div><Label>{t('Max retry delay')}</Label><Input type='number' value={form.data.max_retry_delay_seconds} onChange={e=>form.setData('max_retry_delay_seconds', e.target.value)} /></div><div><Label>{t('Backoff multiplier')}</Label><Input type='number' step='0.1' value={form.data.backoff_multiplier} onChange={e=>form.setData('backoff_multiplier', e.target.value)} /></div><label><input type='checkbox' checked={form.data.jitter_enabled} onChange={e=>form.setData('jitter_enabled', e.target.checked)} /> {t('Jitter enabled')}</label></div></div>
  <div className='grid md:grid-cols-4 gap-3'><label><input type='checkbox' checked={form.data.is_active} onChange={e=>form.setData('is_active', e.target.checked)} /> {t('Active')}</label><label><input type='checkbox' checked={form.data.is_default} onChange={e=>form.setData('is_default', e.target.checked)} /> {t('Default')}</label><label><input type='checkbox' checked={form.data.supports_grounding} onChange={e=>form.setData('supports_grounding', e.target.checked)} /> {t('Supports grounding')}</label><label><input type='checkbox' checked={form.data.supports_citations} onChange={e=>form.setData('supports_citations', e.target.checked)} /> {t('Supports citations')}</label></div>
  {form.errors.provider ? <p className='text-sm text-red-600'>{form.errors.provider}</p>:null}
  <div className='flex gap-2'><Button type='submit'>{t('Save')}</Button><Button asChild variant='secondary'><Link href={route('admin.ai-providers.index')}>{t('Cancel')}</Link></Button></div>
  </form></CardContent></Card></AdminLayout>;
}
