import AdminPageHeader from '@/Components/AdminPageHeader';
import { Badge } from '@/Components/ui/badge';
import { Card, CardContent } from '@/Components/ui/card';
import { useTranslations } from '@/i18n/useTranslations';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head } from '@inertiajs/react';

interface Provider { name:string; slug:string; provider_type:string; client_driver:string; base_url:string|null; api_key_env_name:string|null; default_model:string|null; organization:string|null; is_active:boolean; is_default:boolean; timeout_seconds:number; max_tokens:number|null; temperature:string|null; cost_input_per_1k_tokens:string|null; cost_output_per_1k_tokens:string|null; daily_request_limit:number|null; monthly_request_limit:number|null; daily_cost_limit:string|null; monthly_cost_limit:string|null; env_key_configured:boolean; usage_summary:any; }

export default function Show({ provider }: { provider: Provider }): JSX.Element {
    const { t } = useTranslations();
    return <AdminLayout><Head title={provider.name} /><AdminPageHeader helpKey="admin.aiproviders.show" title={provider.name} description={t('AI provider details.')} /><Card><CardContent className="space-y-2 pt-6 text-sm"><p><strong>{t('Slug')}:</strong> {provider.slug}</p><p><strong>{t('Provider type')}:</strong> {provider.provider_type}</p><p><strong>{t('Driver de ejecución')}:</strong> {provider.client_driver === 'laravel_ai' ? t('Laravel AI SDK') : t('Custom Noticiario')}</p><p><strong>{t('URL base')}:</strong> {provider.base_url || '-'}</p><p><strong>{t('Nombre de variable de entorno de API key')}:</strong> {provider.api_key_env_name || '-'}</p><p><strong>{t('Default model')}:</strong> {provider.default_model || '-'}</p><p><strong>{t('Segundos de espera')}:</strong> {provider.timeout_seconds}</p><p><strong>{t('Tokens máximos')}:</strong> {provider.max_tokens ?? '-'}</p><p><strong>{t('Temperatura')}:</strong> {provider.temperature ?? '-'}</p><p><strong>{t('Coste de tokens de entrada')}:</strong> {provider.cost_input_per_1k_tokens ?? '-'}</p><p><strong>{t('Coste de tokens de salida')}:</strong> {provider.cost_output_per_1k_tokens ?? '-'}</p><p><strong>{t('Límite diario de solicitudes')}:</strong> {provider.daily_request_limit ?? '-'}</p><p><strong>{t('Límite mensual de solicitudes')}:</strong> {provider.monthly_request_limit ?? '-'}</p><p><strong>{t('Status')}:</strong> {provider.is_active ? <Badge>{t('Active')}</Badge> : <Badge variant="danger">{t('Provider is inactive')}</Badge>}</p><p><strong>{t('Environment key status')}:</strong> {provider.env_key_configured ? <Badge>{t('Configured')}</Badge> : <Badge variant="outline">{t('Environment key is not configured')}</Badge>}</p></CardContent></Card></AdminLayout>;
}
