import AdminPageHeader from '@/Components/AdminPageHeader';
import Pagination from '@/Components/Pagination';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import EditorLayout from '@/Layouts/EditorLayout';
import { Head, Link, router } from '@inertiajs/react';
interface Item { id:number; title:string; edition_type:string; location:string|null; scheduled_for:string|null; language:string|null; status:string; target_duration_seconds:number|null; }
interface Props { editions:{data:Item[]; links:Array<{url:string|null; label:string; active:boolean}>}; }
export default function Index({ editions }: Props): JSX.Element {
 const destroy=(id:number)=>{if(window.confirm('Delete this edition?')) router.delete(route('editor.editions.destroy', id));};
 return <EditorLayout><Head title="Editions" /><AdminPageHeader title="Editions" description="Plan bulletin editions." actionLabel="Create edition" actionHref={route('editor.editions.create')} /><Card><CardContent className="overflow-x-auto pt-6"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="px-2 pb-3">Title</th><th className="px-2 pb-3">Type</th><th className="px-2 pb-3">Location</th><th className="px-2 pb-3">Scheduled for</th><th className="px-2 pb-3">Language</th><th className="px-2 pb-3">Status</th><th className="px-2 pb-3">Target duration</th><th className="px-2 pb-3 text-right">Actions</th></tr></thead><tbody>{editions.data.length ? editions.data.map((item)=><tr key={item.id} className="border-b border-slate-100"><td className="px-2 py-3 font-medium">{item.title}</td><td className="px-2 py-3">{item.edition_type}</td><td className="px-2 py-3">{item.location || '-'}</td><td className="px-2 py-3">{item.scheduled_for || '-'}</td><td className="px-2 py-3">{item.language || '-'}</td><td className="px-2 py-3">{item.status}</td><td className="px-2 py-3">{item.target_duration_seconds || '-'}</td><td className="px-2 py-3"><div className="flex justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={route('editor.editions.show', item.id)}>View</Link></Button><Button asChild size="sm" variant="secondary"><Link href={route('editor.editions.edit', item.id)}>Edit</Link></Button><Button size="sm" variant="destructive" onClick={()=>destroy(item.id)}>Delete</Button></div></td></tr>) : <tr><td colSpan={8} className="px-2 py-6 text-center text-slate-500">No editions yet.</td></tr>}</tbody></table><Pagination links={editions.links} /></CardContent></Card></EditorLayout>;
}
