import AdminPageHeader from '@/Components/AdminPageHeader';
import Pagination from '@/Components/Pagination';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import EditorLayout from '@/Layouts/EditorLayout';
import { Head, Link, router } from '@inertiajs/react';
interface T { id:number; name:string; type:string; expected_output_format:string; is_active:boolean; sort_order:number; }
export default function Index({ templates }: { templates:{ data:T[]; links:Array<{url:string|null; label:string; active:boolean}> } }): JSX.Element {
    const destroy = (id:number): void => { if (window.confirm('Delete this prompt template?')) router.delete(route('editor.ai-prompt-templates.destroy', id)); };
    return <EditorLayout><Head title="Prompt Templates" /><AdminPageHeader helpKey="editor.aiprompttemplates.index" title="Prompt Templates" description="Database-backed AI templates." actionLabel="Create Prompt Template" actionHref={route('editor.ai-prompt-templates.create')} /><Card><CardContent className="overflow-x-auto pt-6"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b"><th className="px-2 pb-3 text-left">Name</th><th className="px-2 pb-3 text-left">Type</th><th className="px-2 pb-3 text-left">Output</th><th className="px-2 pb-3 text-left">Active</th><th className="px-2 pb-3 text-left">Sort</th><th className="px-2 pb-3 text-right">Actions</th></tr></thead><tbody>{templates.data.length ? templates.data.map((t)=><tr key={t.id} className="border-b"><td className="px-2 py-3">{t.name}</td><td className="px-2 py-3">{t.type}</td><td className="px-2 py-3">{t.expected_output_format}</td><td className="px-2 py-3">{t.is_active ? 'Yes' : 'No'}</td><td className="px-2 py-3">{t.sort_order}</td><td className="px-2 py-3"><div className="flex justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={route('editor.ai-prompt-templates.show', t.id)}>View</Link></Button><Button asChild size="sm" variant="secondary"><Link href={route('editor.ai-prompt-templates.edit', t.id)}>Edit</Link></Button><Button size="sm" variant="destructive" onClick={()=>destroy(t.id)}>Delete</Button></div></td></tr>) : <tr><td colSpan={6} className="px-2 py-6 text-center">No templates yet.</td></tr>}</tbody></table><Pagination links={templates.links} /></CardContent></Card></EditorLayout>;
}
